# Generated by Django 3.0.5 on 2020-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200522_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', max_length=80000),
        ),
    ]
